configfile: "config/config.yaml"

include: "rules/compare-vcfs.smk"

samples = config['samples']

if not samples:
	samples = ['all']

rule all:
	input:
		expand("results/vcf-stats/{callset}.stats", callset = [c for c in config["callset_vcfs"].keys()]),
		expand("results/intersection/intersection_upset_{sample}.pdf", sample = samples)
